spring:
  profiles: logs-generator
  datasource:
    hikari:
      maximum-pool-size: 1
      minimum-idle: 1
  kafka:
    bootstrap-servers: localhost:9092
    topic: session-request
    producer:
      client-id: targeting-generator
      # value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # compression-type: gzip
      batch-size: 1000
#      ssl:
#        key-store-location: ""
#        trust-store-location: ""
#        key-store-password: 123456
#        trust-store-password: 123456
#        key-password: 123456
#        key-store-type: PKCS12
#        trust-store-type: PKCS12
#        protocol: TLSv1.2
    properties:
      security.protocol: SSL
      ssl.endpoint.identification.algorithm: